# Generated by Django 2.2.7 on 2019-12-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField(help_text='Latitude of Squirrels')),
                ('Longitude', models.FloatField(help_text='Longitude of Squirrels')),
                ('Unique_Squirrel_id', models.CharField(help_text='id of Squirrels', max_length=100)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Whether the sighting happens in the morning or afternoon', max_length=2)),
                ('Date', models.DateField(help_text='Date')),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Other', 'Other')], default='Juvenile', help_text='Type of Squirrels', max_length=10)),
                ('Primary_Fur_Color', models.CharField(choices=[('Gray', 'Gary'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('Other', 'Other')], default='Cinnamon', help_text='Color of Squirrels', max_length=10)),
                ('Location', models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Plane', 'Above Plane'), ('Other', 'Other')], default='Ground Plane', help_text='the location of where the squirrel was when first sighted', max_length=15)),
                ('Specific_Location', models.CharField(help_text='squirrel location added by sighters', max_length=256)),
                ('Running', models.BooleanField(default=False, help_text='Whether the squirrel was running')),
                ('Chasing', models.BooleanField(default=False, help_text='Whether the squirrel was chasing')),
                ('Climbing', models.BooleanField(default=False, help_text='Whether the squirrel was climbing')),
                ('Eating', models.BooleanField(default=False, help_text='Whether the squirrel was eating')),
                ('Foraging', models.BooleanField(default=False, help_text='Whether the squirrel was foraging')),
                ('Other_Activities', models.CharField(help_text='other activies added by sighters', max_length=256)),
                ('Kuks', models.BooleanField(default=False, help_text='Whether the squirrel was heard kukking')),
                ('Quaas', models.BooleanField(default=False, help_text='Whether the squirrel was heard quaaing')),
                ('Moans', models.BooleanField(default=False, help_text='Whether the squirrel was heard moaning')),
                ('Tail_Flags', models.BooleanField(default=False, help_text='Whether the squirrel was seen flagging its tail')),
                ('Tail_Twitches', models.BooleanField(default=False, help_text='Whether the squirrel was seen twitching its tail')),
                ('Approaches', models.BooleanField(default=False, help_text='Whether the squirrel was seen approaching to human')),
                ('Indifferent', models.BooleanField(default=False, help_text='Whether the squirrel was indifferent to human presence')),
                ('Runs_From', models.BooleanField(default=False, help_text='Whether the squirrel was seen running from humans')),
            ],
        ),
    ]
